# Generated by Django 5.2.1 on 2025-06-04 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('prompt_template', models.TextField(help_text='Template with placeholders like {variable_name}', verbose_name='Prompt Template')),
                ('interaction_type', models.CharField(choices=[('suggestion', 'Suggestion'), ('classification', 'Classification'), ('sentiment', 'Sentiment Analysis'), ('summary', 'Summary'), ('response', 'Response Generation')], max_length=20, verbose_name='Interaction Type')),
                ('variables', models.JSONField(blank=True, default=list, help_text='List of variable names used in the template', verbose_name='Variables')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'AI Prompt Template',
                'verbose_name_plural': 'AI Prompt Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AIInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('interaction_type', models.CharField(choices=[('suggestion', 'Suggestion'), ('classification', 'Classification'), ('sentiment', 'Sentiment Analysis'), ('summary', 'Summary'), ('response', 'Response Generation')], max_length=20, verbose_name='Interaction Type')),
                ('input_text', models.TextField(help_text='The text that was sent to AI', verbose_name='Input Text')),
                ('output_text', models.TextField(help_text='The response from AI', verbose_name='Output Text')),
                ('confidence_score', models.FloatField(blank=True, help_text='AI confidence score (0.0 to 1.0)', null=True, verbose_name='Confidence Score')),
                ('processing_time_ms', models.IntegerField(blank=True, null=True, verbose_name='Processing Time (ms)')),
                ('model_used', models.CharField(blank=True, help_text='Which AI model was used', max_length=100, verbose_name='Model Used')),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Additional context data for the interaction', verbose_name='Context Data')),
                ('was_helpful', models.BooleanField(blank=True, help_text='User feedback on whether the AI response was helpful', null=True, verbose_name='Was Helpful')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_interactions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'AI Interaction',
                'verbose_name_plural': 'AI Interactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ai_aiintera_user_id_fb7841_idx'), models.Index(fields=['interaction_type', '-created_at'], name='ai_aiintera_interac_104f89_idx'), models.Index(fields=['model_used'], name='ai_aiintera_model_u_a97761_idx')],
            },
        ),
    ]
