# Generated by Django 5.2.1 on 2025-06-05 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calls', '0001_initial'),
        ('campaigns', '0001_initial'),
        ('contacts', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='Associated campaign if outbound call', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='campaigns.campaign', verbose_name='Campaign'),
        ),
        migrations.AddField(
            model_name='call',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Associated contact record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='contacts.contact', verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='call',
            name='secondary_agent',
            field=models.ForeignKey(blank=True, help_text='Second agent involved in call (transfers, conferences)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_calls', to=settings.AUTH_USER_MODEL, verbose_name='Secondary Agent'),
        ),
        migrations.AddField(
            model_name='callcallback',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callback_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
        migrations.AddField(
            model_name='callcallback',
            name='callback_call',
            field=models.OneToOneField(blank=True, help_text='The actual callback call when made', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callback_origin', to='calls.call', verbose_name='Callback Call'),
        ),
        migrations.AddField(
            model_name='callcallback',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact', verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='callcallback',
            name='original_call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callback_requests', to='calls.call', verbose_name='Original Call'),
        ),
        migrations.AddField(
            model_name='callcallback',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callback_requests', to=settings.AUTH_USER_MODEL, verbose_name='Requested By'),
        ),
        migrations.AddField(
            model_name='calldisposition',
            name='ai_suggested_disposition',
            field=models.ForeignKey(blank=True, help_text='AI-suggested disposition', limit_choices_to={'category': 'disposition'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_suggested_dispositions', to='core.referencedata', verbose_name='AI Suggested Disposition'),
        ),
        migrations.AddField(
            model_name='calldisposition',
            name='call',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disposition', to='calls.call', verbose_name='Call'),
        ),
        migrations.AddField(
            model_name='calldisposition',
            name='disposition',
            field=models.ForeignKey(help_text='Call outcome disposition', limit_choices_to={'category': 'disposition'}, on_delete=django.db.models.deletion.PROTECT, to='core.referencedata', verbose_name='Disposition'),
        ),
        migrations.AddField(
            model_name='callevent',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Agent involved in this event', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Agent'),
        ),
        migrations.AddField(
            model_name='callevent',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='calls.call', verbose_name='Call'),
        ),
        migrations.AddField(
            model_name='callnote',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='callnote',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='calls.call', verbose_name='Call'),
        ),
        migrations.AddField(
            model_name='callqualityassessment',
            name='assessor',
            field=models.ForeignKey(help_text='QA assessor who evaluated this call', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Assessor'),
        ),
        migrations.AddField(
            model_name='callqualityassessment',
            name='call',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_assessment', to='calls.call', verbose_name='Call'),
        ),
        migrations.AddField(
            model_name='calltransfer',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='calls.call', verbose_name='Call'),
        ),
        migrations.AddField(
            model_name='calltransfer',
            name='from_agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to=settings.AUTH_USER_MODEL, verbose_name='From Agent'),
        ),
        migrations.AddField(
            model_name='calltransfer',
            name='to_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to=settings.AUTH_USER_MODEL, verbose_name='To Agent'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['unique_id'], name='calls_call_unique__b7ed31_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['caller_number', '-start_time'], name='calls_call_caller__243ef0_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['called_number', '-start_time'], name='calls_call_called__9b26a3_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['call_direction', '-start_time'], name='calls_call_call_di_c3ba68_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['call_status', '-start_time'], name='calls_call_call_st_8c2b10_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['agent', '-start_time'], name='calls_call_agent_i_7638d0_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['campaign', '-start_time'], name='calls_call_campaig_ea7acb_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['contact', '-start_time'], name='calls_call_contact_04b74b_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['call_date', 'call_direction'], name='calls_call_call_da_a613b1_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['call_date', 'agent'], name='calls_call_call_da_3d41c7_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['call_date', 'campaign'], name='calls_call_call_da_2cc938_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['call_hour', 'call_date'], name='calls_call_call_ho_d16085_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['sla_met', 'call_date'], name='calls_call_sla_met_ba9e98_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['call_status', 'call_date'], name='calls_call_call_st_cb9469_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['hangup_reason', 'call_date'], name='calls_call_hangup__fe6a98_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['legacy_chan_id'], name='calls_call_legacy__ca8adf_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['migration_verified'], name='calls_call_migrati_a26a20_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['ai_analysis_completed', '-start_time'], name='calls_call_ai_anal_ff4e58_idx'),
        ),
        migrations.AddConstraint(
            model_name='call',
            constraint=models.CheckConstraint(condition=models.Q(('audio_quality_score__gte', 0.0), ('audio_quality_score__lte', 10.0)), name='valid_audio_quality_score'),
        ),
        migrations.AddConstraint(
            model_name='call',
            constraint=models.CheckConstraint(condition=models.Q(('ai_sentiment_score__gte', -1.0), ('ai_sentiment_score__lte', 1.0)), name='valid_sentiment_score'),
        ),
        migrations.AddIndex(
            model_name='callcallback',
            index=models.Index(fields=['status', 'scheduled_time'], name='calls_callc_status_339219_idx'),
        ),
        migrations.AddIndex(
            model_name='callcallback',
            index=models.Index(fields=['assigned_to', 'status'], name='calls_callc_assigne_89245c_idx'),
        ),
        migrations.AddIndex(
            model_name='callcallback',
            index=models.Index(fields=['contact', '-created_at'], name='calls_callc_contact_89f99a_idx'),
        ),
        migrations.AddIndex(
            model_name='callcallback',
            index=models.Index(fields=['scheduled_time', 'status'], name='calls_callc_schedul_89cae0_idx'),
        ),
        migrations.AddIndex(
            model_name='calldisposition',
            index=models.Index(fields=['disposition', '-created_at'], name='calls_calld_disposi_e34959_idx'),
        ),
        migrations.AddIndex(
            model_name='calldisposition',
            index=models.Index(fields=['case_created', '-created_at'], name='calls_calld_case_cr_db6bf0_idx'),
        ),
        migrations.AddIndex(
            model_name='calldisposition',
            index=models.Index(fields=['follow_up_required', 'follow_up_date'], name='calls_calld_follow__05198a_idx'),
        ),
        migrations.AddIndex(
            model_name='calldisposition',
            index=models.Index(fields=['callback_requested', '-created_at'], name='calls_calld_callbac_136252_idx'),
        ),
        migrations.AddIndex(
            model_name='calldisposition',
            index=models.Index(fields=['legacy_disposition_id'], name='calls_calld_legacy__74f804_idx'),
        ),
        migrations.AddConstraint(
            model_name='calldisposition',
            constraint=models.CheckConstraint(condition=models.Q(('ai_confidence_score__gte', 0.0), ('ai_confidence_score__lte', 1.0)), name='valid_ai_confidence_score'),
        ),
        migrations.AddIndex(
            model_name='callevent',
            index=models.Index(fields=['call', 'event_time'], name='calls_calle_call_id_cfeb5b_idx'),
        ),
        migrations.AddIndex(
            model_name='callevent',
            index=models.Index(fields=['event_type', 'event_time'], name='calls_calle_event_t_2ac75f_idx'),
        ),
        migrations.AddIndex(
            model_name='callevent',
            index=models.Index(fields=['agent', 'event_time'], name='calls_calle_agent_i_aee41b_idx'),
        ),
        migrations.AddIndex(
            model_name='callnote',
            index=models.Index(fields=['call', '-created_at'], name='calls_calln_call_id_dfd5df_idx'),
        ),
        migrations.AddIndex(
            model_name='callnote',
            index=models.Index(fields=['author', '-created_at'], name='calls_calln_author__ddaa8d_idx'),
        ),
        migrations.AddIndex(
            model_name='callnote',
            index=models.Index(fields=['note_type', '-created_at'], name='calls_calln_note_ty_6d30e6_idx'),
        ),
        migrations.AddIndex(
            model_name='callnote',
            index=models.Index(fields=['is_important', '-created_at'], name='calls_calln_is_impo_06725f_idx'),
        ),
        migrations.AddIndex(
            model_name='callqualityassessment',
            index=models.Index(fields=['assessor', '-created_at'], name='calls_callq_assesso_fa8fac_idx'),
        ),
        migrations.AddIndex(
            model_name='callqualityassessment',
            index=models.Index(fields=['overall_score', '-created_at'], name='calls_callq_overall_1ed248_idx'),
        ),
        migrations.AddIndex(
            model_name='callqualityassessment',
            index=models.Index(fields=['is_calibrated', '-created_at'], name='calls_callq_is_cali_f19889_idx'),
        ),
        migrations.AddIndex(
            model_name='callqualityassessment',
            index=models.Index(fields=['legacy_qa_id'], name='calls_callq_legacy__b1d50b_idx'),
        ),
        migrations.AddConstraint(
            model_name='callqualityassessment',
            constraint=models.CheckConstraint(condition=models.Q(('overall_score__gte', 0.0), ('overall_score__lte', 100.0)), name='valid_overall_score'),
        ),
        migrations.AddConstraint(
            model_name='callqualityassessment',
            constraint=models.CheckConstraint(condition=models.Q(('opening_score__gte', 0.0), ('opening_score__lte', 100.0)), name='valid_opening_score'),
        ),
        migrations.AddConstraint(
            model_name='callqualityassessment',
            constraint=models.CheckConstraint(condition=models.Q(('listening_score__gte', 0.0), ('listening_score__lte', 100.0)), name='valid_listening_score'),
        ),
        migrations.AddConstraint(
            model_name='callqualityassessment',
            constraint=models.CheckConstraint(condition=models.Q(('resolution_score__gte', 0.0), ('resolution_score__lte', 100.0)), name='valid_resolution_score'),
        ),
        migrations.AddConstraint(
            model_name='callqualityassessment',
            constraint=models.CheckConstraint(condition=models.Q(('closing_score__gte', 0.0), ('closing_score__lte', 100.0)), name='valid_closing_score'),
        ),
        migrations.AddConstraint(
            model_name='callqualityassessment',
            constraint=models.CheckConstraint(condition=models.Q(('professionalism_score__gte', 0.0), ('professionalism_score__lte', 100.0)), name='valid_professionalism_score'),
        ),
        migrations.AddIndex(
            model_name='calltransfer',
            index=models.Index(fields=['call', 'transfer_time'], name='calls_callt_call_id_658442_idx'),
        ),
        migrations.AddIndex(
            model_name='calltransfer',
            index=models.Index(fields=['from_agent', '-transfer_time'], name='calls_callt_from_ag_6b2e68_idx'),
        ),
        migrations.AddIndex(
            model_name='calltransfer',
            index=models.Index(fields=['to_agent', '-transfer_time'], name='calls_callt_to_agen_402850_idx'),
        ),
        migrations.AddIndex(
            model_name='calltransfer',
            index=models.Index(fields=['transfer_reason', '-transfer_time'], name='calls_callt_transfe_0689fe_idx'),
        ),
    ]
