# Generated by Django 5.2.2 on 2025-06-24 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Extension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="SIP extension number", max_length=50, unique=True
                    ),
                ),
                (
                    "password",
                    models.CharField(help_text="SIP password", max_length=100),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extension",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "extensions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(help_text="When the call started")),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, help_text="When the call ended", null=True
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        default=0, help_text="Call duration in seconds"
                    ),
                ),
                (
                    "call_status",
                    models.CharField(
                        choices=[
                            ("answered", "Answered"),
                            ("busy", "Busy"),
                            ("no_answer", "No Answer"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="failed",
                        max_length=20,
                    ),
                ),
                (
                    "asterisk_call_id",
                    models.CharField(
                        help_text="Unique call ID from Asterisk",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "callee_extension",
                    models.ForeignKey(
                        help_text="Extension that received the call",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_calls",
                        to="calls.extension",
                    ),
                ),
                (
                    "caller_extension",
                    models.ForeignKey(
                        help_text="Extension that initiated the call",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_calls",
                        to="calls.extension",
                    ),
                ),
            ],
            options={
                "db_table": "call_logs",
                "ordering": ["-start_time"],
            },
        ),
    ]
