# Generated by Django 5.2.2 on 2025-06-08 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmembership',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant that the user is a member of.', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tenantmembership',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_records_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantmembership',
            name='user',
            field=models.ForeignKey(help_text='The user who is a member of the tenant.', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantrole',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this record', on_delete=django.db.models.deletion.PROTECT, related_name='created_records_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantrole',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who soft deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_records_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantrole',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this role belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tenantrole',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_records_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantmembership',
            name='role',
            field=models.ForeignKey(help_text='The role assigned to the user in this tenant.', on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='accounts.tenantrole'),
        ),
        migrations.AddField(
            model_name='userinvitation',
            name='accepted_by',
            field=models.ForeignKey(blank=True, help_text='The user who accepted this invitation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_invitations_accepted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userinvitation',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this record', on_delete=django.db.models.deletion.PROTECT, related_name='created_records_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userinvitation',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who soft deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_records_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userinvitation',
            name='invited_by',
            field=models.ForeignKey(help_text='The user who sent this invitation.', on_delete=django.db.models.deletion.CASCADE, related_name='user_invitations_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userinvitation',
            name='role',
            field=models.ForeignKey(help_text='The role the user will have when they accept.', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='accounts.tenantrole'),
        ),
        migrations.AddField(
            model_name='userinvitation',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant the user is invited to join.', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='userinvitation',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_records_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(help_text='The user this session belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='accounts_us_phone_f54457_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_verified', 'is_active'], name='accounts_us_is_veri_edfcce_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='accounts_us_created_4734df_idx'),
        ),
        migrations.AddIndex(
            model_name='otptoken',
            index=models.Index(fields=['user', 'token_type', 'is_used'], name='accounts_ot_user_id_db0d9b_idx'),
        ),
        migrations.AddIndex(
            model_name='otptoken',
            index=models.Index(fields=['token', 'expires_at'], name='accounts_ot_token_382010_idx'),
        ),
        migrations.AddIndex(
            model_name='otptoken',
            index=models.Index(fields=['expires_at', 'is_used'], name='accounts_ot_expires_90094c_idx'),
        ),
        migrations.AddIndex(
            model_name='platformrole',
            index=models.Index(fields=['user', 'is_active'], name='accounts_pl_user_id_576bb6_idx'),
        ),
        migrations.AddIndex(
            model_name='platformrole',
            index=models.Index(fields=['role', 'is_active'], name='accounts_pl_role_16da3f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='platformrole',
            unique_together={('user', 'role')},
        ),
        migrations.AddIndex(
            model_name='tenantrole',
            index=models.Index(fields=['tenant', 'is_active'], name='accounts_te_tenant__36a63e_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantrole',
            index=models.Index(fields=['name', 'is_active'], name='accounts_te_name_50d23c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantrole',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['user', 'tenant'], name='accounts_te_user_id_05a0e0_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['tenant', 'is_active'], name='accounts_te_tenant__6c4fdd_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['role', 'is_active'], name='accounts_te_role_id_159efa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantmembership',
            unique_together={('user', 'tenant')},
        ),
        migrations.AddIndex(
            model_name='userinvitation',
            index=models.Index(fields=['token'], name='accounts_us_token_15d7e5_idx'),
        ),
        migrations.AddIndex(
            model_name='userinvitation',
            index=models.Index(fields=['email', 'expires_at'], name='accounts_us_email_011bbf_idx'),
        ),
        migrations.AddIndex(
            model_name='userinvitation',
            index=models.Index(fields=['tenant', 'is_accepted'], name='accounts_us_tenant__9d42cf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userinvitation',
            unique_together={('tenant', 'email')},
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'is_active'], name='accounts_us_user_id_91ed82_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_key'], name='accounts_us_session_511f42_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['last_activity'], name='accounts_us_last_ac_a630f7_idx'),
        ),
    ]
