# Generated by Django 5.2.2 on 2025-06-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='usersession',
            name='token_type',
            field=models.CharField(choices=[('session', 'Session'), ('jwt', 'JWT')], default='jwt', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='session_key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
