# Generated by Django 5.2.2 on 2025-06-08 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers_usersession_token_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verified_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_verified_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_2fa_method',
        ),
        migrations.RemoveField(
            model_name='user',
            name='two_factor_enabled',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='token_type',
            field=models.CharField(choices=[('login', 'Login Authentication'), ('email_verification', 'Email Verification'), ('password_reset', 'Password Reset'), ('account_unlock', 'Account Unlock')], help_text='The purpose of this OTP token.', max_length=20, verbose_name='token type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Optional. Phone number for SMS notifications.', max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "+999999999". Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')], verbose_name='phone number'),
        ),
    ]
