# Generated by Django 5.2.2 on 2025-08-02 15:44

import django.contrib.postgres.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0002_alter_referencedata_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencedatatype',
            name='allowed_metadata_keys',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, help_text='Allowed keys for metadata JSON (system-managed types enforce this strictly)', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='referencedatatype',
            name='description',
            field=models.TextField(blank=True, help_text='Human-readable description of this reference data type'),
        ),
        migrations.AlterField(
            model_name='referencedatatype',
            name='is_system_managed',
            field=models.BooleanField(default=False, help_text='If True, this type is controlled by system code and cannot be modified via API. CANNOT be True if is_tenant_specific=True.'),
        ),
        migrations.AlterField(
            model_name='referencedatatype',
            name='is_tenant_specific',
            field=models.BooleanField(default=False, help_text='If True, this type can have different values per tenant. CANNOT be True if is_system_managed=True.'),
        ),
        migrations.AlterField(
            model_name='referencedatatype',
            name='name',
            field=models.CharField(help_text="Unique name identifier (e.g., 'product_categories'). Must be lowercase with underscores for system-managed types.", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='referencedatatype',
            name='validation_schema',
            field=models.JSONField(blank=True, help_text='JSON Schema for validating metadata (applies to tenant-specific values)', null=True),
        ),
        migrations.AddConstraint(
            model_name='referencedatatype',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_system_managed', True), _negated=True), ('is_tenant_specific', False), _connector='OR'), name='system_managed_cannot_be_tenant_specific'),
        ),
        migrations.AddConstraint(
            model_name='referencedatatype',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_tenant_specific', True), _negated=True), ('is_system_managed', False), _connector='OR'), name='tenant_specific_cannot_be_system_managed'),
        ),
    ]
