# Generated by Django 5.2.2 on 2025-08-02 15:57

import django.contrib.postgres.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0003_alter_referencedatatype_allowed_metadata_keys_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referencedatatype',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='referencedatatype',
            name='system_managed_cannot_be_tenant_specific',
        ),
        migrations.RemoveConstraint(
            model_name='referencedatatype',
            name='tenant_specific_cannot_be_system_managed',
        ),
        migrations.AlterField(
            model_name='referencedatatype',
            name='allowed_metadata_keys',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Allowed metadata keys', size=None),
        ),
        migrations.AlterField(
            model_name='referencedatatype',
            name='description',
            field=models.TextField(blank=True, help_text='Human-readable description'),
        ),
        migrations.AlterField(
            model_name='referencedatatype',
            name='is_system_managed',
            field=models.BooleanField(default=False, help_text='Managed by system code'),
        ),
        migrations.AlterField(
            model_name='referencedatatype',
            name='is_tenant_specific',
            field=models.BooleanField(default=False, help_text='Customizable per tenant'),
        ),
        migrations.AlterField(
            model_name='referencedatatype',
            name='name',
            field=models.CharField(help_text="Unique name identifier (e.g., 'product_categories')", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='referencedatatype',
            name='validation_schema',
            field=models.JSONField(blank=True, help_text='Validation schema', null=True),
        ),
        migrations.AddConstraint(
            model_name='referencedatatype',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_system_managed', True), _negated=True), ('is_tenant_specific', False), _connector='OR'), name='no_system_managed_tenant_specific'),
        ),
        migrations.AlterModelTable(
            name='referencedatatype',
            table=None,
        ),
    ]
