# Generated by Django 5.2.2 on 2025-07-31 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_alter_auditlog_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='object_type',
            field=models.ForeignKey(blank=True, help_text='Type of object that was affected', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
