# Generated by Django 5.2.2 on 2025-07-31 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_auditlog_object_type'),
        ('tenants', '0002_alter_tenantinvitation_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant where this action occurred', null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
    ]
